# Configuration for an instance accelerator in the AccelTran design space

tile:
  tile_b: 1
  tile_x: 8
  tile_y: 8

non_linearity: 'gelu'

pe: 64

lanes_per_pe: 64

mac_per_lane: 16

batch_size: 4

activation_buffer_size: 16

weight_buffer_size: 32

mask_buffer_size: 4

main_memory:
  type: 'rram'
  banks: 16
  ranks: 2
  channels: 2
