# Configuration for an instance accelerator in the AccelTran design space

tile:
  tile_b: 1
  tile_x: 16
  tile_y: 16

non_linearity: 'gelu'

pe: 256

lanes_per_pe: 4

mac_per_lane: 16

batch_size: 4

activation_buffer_size: 16

weight_buffer_size: 32

mask_buffer_size: 4

loop_unrolling: 'b_i_j_k'

main_memory:
  type: 'rram'
  banks: 16
  ranks: 2
  channels: 2

scheduler:
  compute_ops:
    tiled: True
    batch_size: 16
  memory_ops:
    tiled: False
    batch_size: 1
